services:
  - type: web
    name: loansphere
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m flask db upgrade && gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        placeholder: mysql+pymysql://username:password@hostname/dbname
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "True"
      - key: MAIL_USERNAME
        placeholder: your-email@gmail.com
      - key: MAIL_PASSWORD
        placeholder: your-smtp-app-password
      - key: MAIL_DEFAULT_SENDER
        placeholder: no-reply@loansphere.bank
